# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HvN7PwGFwTXAWopzjJ86FNVThTUy46ys
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('zomato.csv')
df.head()

!pip install seaborn
!pip install plotly

df.drop_duplicates(inplace=True)

df = df.dropna(subset=['rate', 'location', 'cuisines', 'rest_type', 'approx_cost(for two people)'])

# Remove '/5' from rate and convert to float
df['rate'] = df['rate'].apply(lambda x: str(x).split('/')[0].strip() if isinstance(x, str) else x)
df['rate'] = pd.to_numeric(df['rate'], errors='coerce')

df['cost'] = df['approx_cost(for two people)'].str.replace(',', '')
df['cost'] = pd.to_numeric(df['cost'], errors='coerce')

df.dropna(subset=['rate', 'cost'], inplace=True)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 5))
rest_types = df['rest_type'].value_counts()[:10]
sns.barplot(x=rest_types.values, y=rest_types.index, palette='viridis')
plt.title('Top 10 Restaurant Types')
plt.xlabel('Count')
plt.show()

#Most common cusinies
plt.figure(figsize=(10, 5))
cuisines = df['cuisines'].value_counts()[:10]
sns.barplot(x=cuisines.values, y=cuisines.index, palette='coolwarm')
plt.title('Top 10 Cuisines')
plt.xlabel('Count')
plt.show()

#Average Rating by Restaurant Type
avg_rating = df.groupby('rest_type')['rate'].mean().sort_values(ascending=False)[:10]
plt.figure(figsize=(10, 5))
sns.barplot(x=avg_rating.values, y=avg_rating.index, palette='magma')
plt.title('Average Rating by Restaurant Type')
plt.xlabel('Average Rating')
plt.show()

#Cost vs Rating Scatter Plot
plt.figure(figsize=(8, 5))
sns.scatterplot(x='cost', y='rate', data=df, alpha=0.5)
plt.title('Cost for Two vs Rating')
plt.xlabel('Cost for Two (INR)')
plt.ylabel('Rating')
plt.show()

# Online Order vs Rating
online_order_rating = df.groupby('online_order')['rate'].mean()
online_order_rating.plot(kind='bar', color=['orange', 'green'])
plt.title('Average Rating by Online Ordering Availability')
plt.ylabel('Average Rating')
plt.xticks(rotation=0)
plt.show()